language: php
php: ["7.0"]
sudo: false
dist: trusty

install:
- wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s -
script:
- wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - SoupFFA-McpeBooster
