name: SoupFFA
main: SoupFFA\SoupFFA
version: 2.3.0
api: 3.0.0-ALPHA9
author: McpeBooster
website: twitter.com/McpeBooster

commands:
  soupffa:
    description: Join SoupFFA directly per Command
